volumes:
  cache_data: null

services:
  ubuntu:
    image: ubuntu:24.04
    volumes:
      - ..:/workspace
      - cache_data:/home/ubuntu/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
